name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-tool: ['gradle', 'maven']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: ${{ matrix.build-tool }}
        
    - name: Build with Maven
      if: matrix.build-tool == 'maven'
      run: mvn -B package --file pom.xml
      
    - name: Build with Gradle
      if: matrix.build-tool == 'gradle'
      run: ./gradlew build
      
    - name: Run Maven tests
      if: matrix.build-tool == 'maven'
      run: mvn test
      
    - name: Run Gradle tests
      if: matrix.build-tool == 'gradle'
      run: ./gradlew test